services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: https://beszel.schreinerwirt-schwangau.de
    ports:
      - 127.0.0.1:8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.schreinerwirt-schwangau.de`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.tls=true
      - traefik.http.routers.beszel.tls.certresolver=letsencrypt
      - traefik.http.services.beszel.loadbalancer.server.port=8090
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://localhost:8090
      TOKEN: ${TOKEN}
      KEY: ${PUB_KEY}
networks:
  traefik_proxy:
    external: true
